alias:
  Bach:
    - Johann Sebastian Bach
  Beethoven:
    - Ludwig van Beethoven
  Chopin:
    - Frédéric Chopin
  Elgar:
    - Edward Elgar
  Faure:
    - Gabriel Fauré
  Mozart:
    - Wolfgang Amadeus Mozart
  Debussy:
    - Claude Debussy
  Rachmaninov:
    - Rachmaninoff
  Ravel:
    - Maurice Ravel
  Schumann:
    - Robert Schumann
  Yiruma:
    - Lee Ru-ma
