alias:
  Bach:
    - Johann Sebastian Bach
  Beethoven:
    - Ludwig van Beethoven
  Faure:
    - Gabriel Fauré
  Mozart:
    - Wolfgang Amadeus Mozart
  Debussy:
    - Claude Debussy
  Rachmaninov:
    - Rachmaninoff
  Schumann:
    - Robert Schumann
  Yiruma:
    - Lee Ru-ma
